import Footer from './components/Footer';
import Nav from './components/Nav';
import './global.css';
import { Titillium_Web } from 'next/font/google'

const titillium = Titillium_Web({ subsets: ["latin"], weight: ['200'] })

export const metadata = {
  title: 'FlickrApp by Alejandro Rodriguez',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${titillium.className}`}>
        <div className='main'>
            <div className='gradient' />
        </div>
        <main className='app'>
          <Nav />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
